# Generated by Django 3.2.4 on 2022-04-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
